# Cross-compilation from macOS to Windows ARM64.
#
# Required:
#   - MINGW_W64_ARM64_ROOT or LLVM_MINGW_ROOT pointing at a toolchain containing
#     aarch64-w64-mingw32-gcc/g++/windres
#   - OPENSSL_ROOT_DIR pointing at a Windows ARM64 OpenSSL prefix

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR ARM64)

if(DEFINED ENV{MINGW_W64_ARM64_ROOT})
    set(TOOLCHAIN_ROOT $ENV{MINGW_W64_ARM64_ROOT})
elseif(DEFINED ENV{LLVM_MINGW_ROOT})
    set(TOOLCHAIN_ROOT $ENV{LLVM_MINGW_ROOT})
else()
    message(FATAL_ERROR "Set MINGW_W64_ARM64_ROOT or LLVM_MINGW_ROOT to a Windows ARM64 mingw toolchain")
endif()

set(TOOLCHAIN_PREFIX aarch64-w64-mingw32)

set(CMAKE_C_COMPILER   ${TOOLCHAIN_ROOT}/bin/${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_ROOT}/bin/${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_RC_COMPILER  ${TOOLCHAIN_ROOT}/bin/${TOOLCHAIN_PREFIX}-windres)

set(CMAKE_FIND_ROOT_PATH
    ${TOOLCHAIN_ROOT}/${TOOLCHAIN_PREFIX}
    ${TOOLCHAIN_ROOT}
)

if(DEFINED CMAKE_PREFIX_PATH)
    list(APPEND CMAKE_FIND_ROOT_PATH ${CMAKE_PREFIX_PATH})
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
