#pragma once

#include <QString>
#include <QWidget>

namespace chatui {

inline QString cyberpunkStyleSheet() {
    return QStringLiteral(
        "QWidget {"
        "  background-color: #080612;"
        "  color: #9afcff;"
        "  font-family: Menlo, Monaco, monospace;"
        "}"
        "QDialog, QTabWidget::pane {"
        "  background-color: #0b0817;"
        "  border: 1px solid #14d8ff;"
        "}"
        "QLabel { color: #9afcff; }"
        "QLabel#pageTitle {"
        "  color: #d6ffff;"
        "  font-size: 20px;"
        "  font-weight: 700;"
        "  padding: 4px 0 8px 0;"
        "  border-bottom: 1px solid rgba(255, 59, 92, 0.65);"
        "  margin-bottom: 8px;"
        "}"
        "QGroupBox {"
        "  color: #8ffbff;"
        "  border: 1px solid #ff355e;"
        "  border-radius: 8px;"
        "  margin-top: 12px;"
        "  padding-top: 12px;"
        "  background-color: #0b0d1a;"
        "}"
        "QGroupBox::title {"
        "  subcontrol-origin: margin;"
        "  left: 12px;"
        "  padding: 0 6px;"
        "  color: #ff5978;"
        "}"
        "QTabBar::tab {"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #180714, stop:1 #101b26);"
        "  color: #8efcff;"
        "  border: 1px solid #ff365f;"
        "  border-bottom-color: #14d8ff;"
        "  border-top-left-radius: 6px;"
        "  border-top-right-radius: 6px;"
        "  padding: 8px 16px;"
        "  margin-right: 4px;"
        "}"
        "QTabBar::tab:selected {"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #1a0d20, stop:1 #132736);"
        "  color: #e8ffff;"
        "  border-color: #14d8ff;"
        "}"
        "QTabBar::tab:hover {"
        "  color: #ffffff;"
        "  border-color: #ff6d8a;"
        "}"
        "QLineEdit, QPlainTextEdit, QSpinBox, QComboBox, QAbstractSpinBox {"
        "  background-color: #050813;"
        "  color: #97ffff;"
        "  border: 1px solid #14d8ff;"
        "  border-radius: 4px;"
        "  padding: 6px 8px;"
        "  selection-background-color: #ff355e;"
        "  selection-color: #f7ffff;"
        "}"
        "QLineEdit:focus, QPlainTextEdit:focus, QSpinBox:focus, QComboBox:focus, QAbstractSpinBox:focus {"
        "  border: 1px solid #ff355e;"
        "}"
        "QPushButton {"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #170713, stop:1 #0d2430);"
        "  color: #a2ffff;"
        "  border: 1px solid #ff355e;"
        "  border-radius: 5px;"
        "  padding: 7px 14px;"
        "  font-weight: 600;"
        "}"
        "QPushButton:hover {"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #211022, stop:1 #123243);"
        "  border-color: #14d8ff;"
        "}"
        "QPushButton:pressed {"
        "  background: #0a1a24;"
        "}"
        "QPushButton:disabled {"
        "  color: #54737a;"
        "  border-color: #4c2530;"
        "  background: #101018;"
        "}"
        "QCheckBox { color: #9afcff; spacing: 8px; }"
        "QCheckBox::indicator {"
        "  width: 14px;"
        "  height: 14px;"
        "  border: 1px solid #14d8ff;"
        "  background: #050813;"
        "}"
        "QCheckBox::indicator:checked {"
        "  background: #ff355e;"
        "  border-color: #ff355e;"
        "}"
        "QTableWidget {"
        "  background-color: #04070f;"
        "  alternate-background-color: #08111a;"
        "  color: #96ffff;"
        "  gridline-color: rgba(20, 216, 255, 0.3);"
        "  border: 1px solid #14d8ff;"
        "  selection-background-color: rgba(255, 53, 94, 0.35);"
        "  selection-color: #ffffff;"
        "}"
        "QHeaderView::section {"
        "  background-color: #0f1422;"
        "  color: #ff6f8d;"
        "  border: 1px solid #14d8ff;"
        "  padding: 6px;"
        "  font-weight: 700;"
        "}"
        "QTableCornerButton::section {"
        "  background-color: #0f1422;"
        "  border: 1px solid #14d8ff;"
        "}"
        "QScrollBar:vertical, QScrollBar:horizontal {"
        "  background: #090d18;"
        "  border: 1px solid #13202e;"
        "  margin: 0px;"
        "}"
        "QScrollBar::handle:vertical, QScrollBar::handle:horizontal {"
        "  background: #14d8ff;"
        "  min-height: 24px;"
        "  min-width: 24px;"
        "}"
        "QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {"
        "  background: #ff355e;"
        "}"
        "QScrollBar::add-line, QScrollBar::sub-line, QScrollBar::add-page, QScrollBar::sub-page {"
        "  background: none;"
        "  border: none;"
        "}"
        "QDialogButtonBox QPushButton { min-width: 96px; }"
        "QFrame#forumCard {"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #0e0a1c, stop:1 #0a1723);"
        "  border: 1px solid rgba(20, 216, 255, 0.72);"
        "  border-left: 3px solid #ff355e;"
        "  border-radius: 10px;"
        "}"
        "QFrame#forumCard:hover {"
        "  border-color: #ff5f80;"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #150d25, stop:1 #0c2330);"
        "}"
        "QLabel#forumChannelChip {"
        "  color: #ff93aa;"
        "  background-color: rgba(255, 53, 94, 0.12);"
        "  border: 1px solid rgba(255, 53, 94, 0.70);"
        "  border-radius: 10px;"
        "  padding: 2px 10px;"
        "  font-weight: 700;"
        "}"
        "QLabel#forumSender {"
        "  color: #dffeff;"
        "  font-size: 15px;"
        "  font-weight: 700;"
        "}"
        "QLabel#forumMeta {"
        "  color: #6fe7ff;"
        "  font-size: 11px;"
        "}"
        "QLabel#forumExcerpt {"
        "  color: #bafcff;"
        "  font-size: 13px;"
        "  line-height: 1.35em;"
        "}"
        "QLabel#forumStatusChip {"
        "  color: #90f8ff;"
        "  background-color: rgba(20, 216, 255, 0.10);"
        "  border: 1px solid rgba(20, 216, 255, 0.60);"
        "  border-radius: 9px;"
        "  padding: 2px 8px;"
        "}"
        "QPushButton#forumGhostButton {"
        "  background: transparent;"
        "  color: #8ffcff;"
        "  border: 1px solid rgba(20, 216, 255, 0.55);"
        "}"
        "QPushButton#forumGhostButton:hover {"
        "  background: rgba(20, 216, 255, 0.08);"
        "  border-color: #14d8ff;"
        "}"
        "QPushButton#forumAccentButton {"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #230813, stop:1 #0f2632);"
        "  color: #f4ffff;"
        "  border: 1px solid #ff355e;"
        "}"
        "QPushButton#forumAccentButton:hover {"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #34101d, stop:1 #133445);"
        "}"
        "QFrame#audioPreviewCard {"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #120a1f, stop:1 #0a1824);"
        "  border: 1px solid rgba(20, 216, 255, 0.75);"
        "  border-left: 4px solid #ff355e;"
        "  border-radius: 12px;"
        "}"
        "QFrame#imagePreviewCard {"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #10122a, stop:1 #101927);"
        "  border: 1px solid rgba(20, 216, 255, 0.82);"
        "  border-left: 4px solid #14d8ff;"
        "  border-radius: 12px;"
        "}"
        "QLabel#imagePreviewSurface {"
        "  background: qradialgradient(cx:0.5, cy:0.45, radius:1.0, stop:0 #15263a, stop:0.55 #0a1322, stop:1 #060910);"
        "  border: 1px solid rgba(20, 216, 255, 0.55);"
        "  border-radius: 12px;"
        "  padding: 12px;"
        "  color: #b8ffff;"
        "}"
        "QLabel#imageMetaLabel {"
        "  color: #9af7ff;"
        "  background: rgba(20, 216, 255, 0.07);"
        "  border: 1px solid rgba(20, 216, 255, 0.32);"
        "  border-radius: 8px;"
        "  padding: 10px;"
        "}"
        "QFrame#videoPreviewCard {"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #1a0916, stop:1 #0a1824);"
        "  border: 1px solid rgba(255, 53, 94, 0.82);"
        "  border-left: 4px solid #ff355e;"
        "  border-radius: 12px;"
        "}"
        "QLabel#videoPosterSurface {"
        "  background: qradialgradient(cx:0.55, cy:0.4, radius:1.0, stop:0 #2d0d1f, stop:0.55 #12091a, stop:1 #080910);"
        "  border: 1px solid rgba(255, 53, 94, 0.55);"
        "  border-radius: 12px;"
        "  padding: 12px;"
        "  color: #ffd1db;"
        "}"
        "QLabel#videoMetaLabel {"
        "  color: #ffc0ce;"
        "  background: rgba(255, 53, 94, 0.08);"
        "  border: 1px solid rgba(255, 53, 94, 0.30);"
        "  border-radius: 8px;"
        "  padding: 10px;"
        "}"
        "QLabel#audioPreviewTitle {"
        "  color: #e7ffff;"
        "  font-size: 17px;"
        "  font-weight: 700;"
        "}"
        "QLabel#audioAttachmentMeta {"
        "  color: #8efaff;"
        "  font-size: 12px;"
        "}"
        "QLabel#audioPrivacyBadge {"
        "  color: #ff95aa;"
        "  background-color: rgba(255, 53, 94, 0.10);"
        "  border: 1px solid rgba(255, 53, 94, 0.70);"
        "  border-radius: 10px;"
        "  padding: 3px 10px;"
        "  font-weight: 700;"
        "}"
        "QLabel#audioTranscriptLabel {"
        "  color: #dffeff;"
        "  font-size: 13px;"
        "  font-weight: 700;"
        "}"
        "QLabel#audioTranscriptStatus {"
        "  color: #7fe9ff;"
        "  font-size: 11px;"
        "}"
    );
}

inline void applyCyberpunkTheme(QWidget* widget) {
    if (!widget) return;
    widget->setStyleSheet(cyberpunkStyleSheet());
}

inline QString errorColorStyle() {
    return QStringLiteral("color:#ff4d6d;");
}

} // namespace chatui
