#pragma once

#include <QMainWindow>
#include "rpc/RpcClient.hpp"
#include "app/DaemonController.hpp"
#include "app/MinerController.hpp"

class DashboardPage;
class SendPage;
class ReceivePage;
class TransactionsPage;
class NetworkGraphPage;
class WalletPage;
class MiningPage;
class RpcConsolePage;
class TerminalPage;
class NodeWindow;
class ChatWindow;
class MailWindow;
class WalletManagerWindow;
class QAction;
class QComboBox;
class QCheckBox;
class QLineEdit;
class QTextEdit;
class QTabWidget;
class QLabel;
class QTimer;
class QPlainTextEdit;
class QWidget;
class QProgressBar;
class QPushButton;
class QToolButton;
class QResizeEvent;
class QShowEvent;
class QTableWidget;

class MainWindow : public QMainWindow {
    Q_OBJECT
public:
    explicit MainWindow(QWidget* parent = nullptr);
    ~MainWindow() override;

protected:
    void resizeEvent(QResizeEvent* event) override;
    void showEvent(QShowEvent* event) override;
    void closeEvent(QCloseEvent* event) override;

private:
    void buildUi();
    void loadSettings();
    void saveSettings();
    void applyRpcSettings();
    void applyAutomaticBackendDefaults();
    void applyConfigBackedDefaults();
    void persistLocalRpcConfig();
    QString managedWalletRootForDataDir(const QString& dataDir) const;
    QString managedWalletPathForName(const QString& walletName, const QString& format) const;
    QString legacyWalletPathForDataDir(const QString& dataDir) const;
    QStringList parsePeerEntryList(const QString& text) const;
    void refreshWalletSessionState();
    void refreshWalletRegistry();
    void createWalletSession();
    void openWalletSession();
    void closeWalletSession();
    void deleteWalletSession();
    void syncWalletPathFromDataDir();
    QString defaultDataDirForNetwork(const QString& network) const;
    QString defaultConfigPathForDataDir(const QString& dataDir) const;
    QUrl defaultRpcUrlForNetwork(const QString& network) const;
    void bootstrapBackendAndRefresh(int retries = 8, int generation = -1);
    void setBackendState(const QString& text, bool error = false);
    void showBackendStartupFailure(const QString& detail);
    void clearBackendStartupFailure();
    void refreshAll();
    void refreshCurrentMainTab();
    void refreshVisibleNodeSection();
    void refreshVisibleWalletManager();
    void refreshVisibleChatSection();
    void refreshVisibleMailSection();
    void refreshSyncState();
    void refreshNodeInformation();
    void updateSyncOverlay(const QJsonObject& blockchainInfo);
    void setStartupOverlayVisible(bool visible);
    void layoutStartupOverlay();
    void updateResponsiveLayout();
    void openNodeWindow(const QString& section = QString());
    void openWalletManagerWindow();
    void openChatWindow(const QString& section = QString());
    void openMailWindow(const QString& section = QString());
    QString formatSyncEta(double hours_remaining) const;
    QString formatSyncTimestamp(qint64 epoch_seconds) const;
    void updateApprovalIndicators();
    void updateSyncStatusBar(const QString& text, bool busy, double progress = -1.0);
    void updateStatusIcons();
    void setStartupProgressBusy(bool busy, const QString& text = QString());
    void toggleSyncOverlay();
    void startBackend();
    void launchBackendProcess();
    void handleBackendPortConflict(const QString& detail = QString());
    void stopBackend();
    QString guessedDaemonPath() const;
    void setConnectionStatus(const QString& text, bool error = false);
    void refreshCheckpointManager();
    void setAdvancedModeEnabled(bool enabled);
    void applyAdvancedModeUi();

    RpcClient rpc_;
    DaemonController daemon_;
    MinerController miner_;

    QLineEdit* rpcUrlEdit_{nullptr};
    QLineEdit* rpcUserEdit_{nullptr};
    QLineEdit* rpcPasswordEdit_{nullptr};
    QCheckBox* rpcTlsCheck_{nullptr};
    QCheckBox* rpcTlsAllowSelfSignedCheck_{nullptr};
    QLineEdit* rpcTlsCertPathEdit_{nullptr};
    QLineEdit* rpcTlsKeyPathEdit_{nullptr};
    QLineEdit* rpcTlsCaPathEdit_{nullptr};
    QLineEdit* daemonPathEdit_{nullptr};
    QLineEdit* dataDirEdit_{nullptr};
    QCheckBox* advancedModeCheck_{nullptr};
    QWidget* walletManagerPage_{nullptr};
    QLabel* walletRootValue_{nullptr};
    QLineEdit* walletNameEdit_{nullptr};
    QLineEdit* walletPathEdit_{nullptr};
    QLineEdit* walletPassEdit_{nullptr};
    QComboBox* walletFormatCombo_{nullptr};
    QComboBox* walletKdfCombo_{nullptr};
    QTableWidget* walletListTable_{nullptr};
    QLineEdit* directPeersEdit_{nullptr};
    QLineEdit* seedPeersEdit_{nullptr};
    QComboBox* networkCombo_{nullptr};
    QLabel* daemonStatusLabel_{nullptr};
    QLabel* syncStatusBarLabel_{nullptr};
    QLabel* walletSessionStatusLabel_{nullptr};
    QLabel* approvalBadgeLabel_{nullptr};
    QLabel* approvalStatusBarLabel_{nullptr};
    QProgressBar* syncStatusProgressBar_{nullptr};
    QTabWidget* tabs_{nullptr};
    NodeWindow* nodeWindow_{nullptr};
    ChatWindow* chatWindow_{nullptr};
    MailWindow* mailWindow_{nullptr};
    WalletManagerWindow* walletManagerWindow_{nullptr};
    QWidget* settingsPage_{nullptr};
    QWidget* nodeInfoPage_{nullptr};
    QWidget* consoleHubPage_{nullptr};
    QWidget* minerOutputPage_{nullptr};
    DashboardPage* dashboardPage_{nullptr};
    SendPage* sendPage_{nullptr};
    ReceivePage* receivePage_{nullptr};
    TransactionsPage* transactionsPage_{nullptr};
    NetworkGraphPage* networkGraphPage_{nullptr};
    WalletPage* walletPage_{nullptr};
    MiningPage* miningPage_{nullptr};
    RpcConsolePage* rpcConsolePage_{nullptr};
    TerminalPage* terminalPage_{nullptr};
    QPlainTextEdit* systemLogView_{nullptr};
    QPlainTextEdit* minerOutputView_{nullptr};
    QLabel* nodeClientVersionValue_{nullptr};
    QLabel* nodeRpcTargetValue_{nullptr};
    QLabel* nodeDataDirValue_{nullptr};
    QLabel* nodeNetworkValue_{nullptr};
    QLabel* nodeConnectionValue_{nullptr};
    QLabel* nodeHeightValue_{nullptr};
    QLabel* nodeSyncValue_{nullptr};
    QLabel* nodeApprovalValue_{nullptr};
    QLabel* nodeMempoolValue_{nullptr};
    QLabel* nodePeerModeValue_{nullptr};
    QLabel* checkpointModeValue_{nullptr};
    QLabel* checkpointHeightValue_{nullptr};
    QLabel* checkpointHashValue_{nullptr};
    QLabel* checkpointGuardValue_{nullptr};
    QLabel* portMappingValue_{nullptr};
    QPushButton* checkpointPinButton_{nullptr};
    QPushButton* checkpointClearButton_{nullptr};
    QPushButton* checkpointRefreshButton_{nullptr};
    QWidget* startupOverlay_{nullptr};
    QWidget* startupPanel_{nullptr};
    QLabel* startupIntroLabel_{nullptr};
    QLabel* startupSummaryLabel_{nullptr};
    QLabel* startupBlocksLeftLabel_{nullptr};
    QLabel* startupLastBlockLabel_{nullptr};
    QLabel* startupProgressLabel_{nullptr};
    QLabel* startupRateLabel_{nullptr};
    QLabel* startupEtaLabel_{nullptr};
    QLabel* startupStateLabel_{nullptr};
    QLabel* startupApprovalLabel_{nullptr};
    QLabel* startupValidatedPeersLabel_{nullptr};
    QLabel* startupLockedBalanceLabel_{nullptr};
    QProgressBar* startupProgressBar_{nullptr};
    QPushButton* startupHideButton_{nullptr};
    QToolButton* nodeWindowButton_{nullptr};
    QToolButton* chatWindowButton_{nullptr};
    QToolButton* mailWindowButton_{nullptr};
    QToolButton* syncDetailsButton_{nullptr};
    QToolButton* peerActivityButton_{nullptr};
    QToolButton* networkActivityButton_{nullptr};
    QToolButton* topRefreshButton_{nullptr};
    QAction* openNodeAction_{nullptr};
    QAction* openChatAction_{nullptr};
    QAction* openMailAction_{nullptr};
    QAction* advancedModeAction_{nullptr};
    QPushButton* createWalletButton_{nullptr};
    QPushButton* openWalletButton_{nullptr};
    QPushButton* closeWalletButton_{nullptr};
    QPushButton* deleteWalletButton_{nullptr};
    QPushButton* refreshWalletsButton_{nullptr};
    QTimer* refreshTimer_{nullptr};
    QTimer* startupProgressPulseTimer_{nullptr};
    QTimer* refreshCooldownTimer_{nullptr};
    bool backendBootstrapInProgress_{false};
    bool backendStartupFailed_{false};
    bool backendPortConflictPending_{false};
    bool minerProcessRunning_{false};
    QString backendStartupFailureText_;
    QString backendPortConflictDetail_;
    QString autoDaemonPath_;
    QString autoDataDir_;
    QString autoWalletPath_;
    QString autoRpcUrl_;
    QString autoRpcUser_;
    QString autoRpcPassword_;
    QString autoDirectPeers_;
    QString autoSeedPeers_;
    bool syncOverlayDismissed_{false};
    bool syncOverlayPinned_{false};
    double lastSyncProgress_{-1.0};
    qint64 lastSyncSampleMs_{0};
    bool approvalKnown_{false};
    bool chainApproved_{true};
    qint64 lockedBalanceSats_{0};
    int validatedPeerCount_{0};
    bool networkSyncing_{false};
    bool networkActive_{true};
    bool advancedModeEnabled_{false};
    int connectedPeerCount_{0};
    int startupProgressPulseValue_{220};
    int startupProgressPulseDirection_{1};
    bool refreshWaveInFlight_{false};
    bool refreshWaveQueued_{false};
    int backendBootstrapGeneration_{0};
};
